namespace URBE.Pokemon.API.Services;

public static class AnonUserNameGenerator
{
    private static readonly string[] Nouns = 
    {
        "Aardvark",
        "Albatross",
        "Alligator",
        "Alpaca",
        "Ant",
        "Anteater",
        "Antelope",
        "Ape",
        "Armadillo",
        "Donkey",
        "Baboon",
        "Badger",
        "Barracuda",
        "Bat",
        "Bear",
        "Beaver",
        "Bee",
        "Beetle",
        "Binturong",
        "Bird",
        "Boar",
        "Pig",
        "Bobcat",
        "Budgerigar",
        "Buffalo",
        "Bull",
        "Butterfly",
        "Camel",
        "Capybara",
        "Cat",
        "Chamois",
        "Cheetah",
        "Chicken",
        "Chimpanzee",
        "Chinchilla",
        "Chough",
        "Coati",
        "Cobra",
        "Cockroach",
        "Cod",
        "Cormorant",
        "Cow",
        "Crab",
        "Crane",
        "Cricket",
        "Crocodile",
        "Crow",
        "Curlew",
        "Deer",
        "Dinosaur",
        "Dog",
        "Shark",
        "Dolphin",
        "Dove",
        "Dragonfly",
        "Duck",
        "Dugong",
        "Dunlin",
        "Eagle",
        "Echidna",
        "Eel",
        "Elephant",
        "Elephant seal",
        "Elk",
        "Emu",
        "Falcon",
        "Ferret",
        "Finch",
        "Fish",
        "Flamingo",
        "Fly",
        "Fox",
        "Frog",
        "Gazelle",
        "Gecko",
        "Gerbil",
        "Giant panda",
        "Giraffe",
        "Gnat",
        "Gnu",
        "Goat",
        "Goldfinch",
        "Goosander",
        "Goose",
        "Gorilla",
        "Goshawk",
        "Grasshopper",
        "Grouse",
        "Guanaco",
        "Guinea fowl",
        "Guinea pig",
        "Gull",
        "Hamster",
        "Hare",
        "Hawk",
        "Hedgehog",
        "Hermit crab",
        "Heron",
        "Herring",
        "Hippopotamus",
        "Hornet",
        "Horse",
        "Human",
        "Hummingbird",
        "Hyena",
        "Ibex",
        "Ibis",
        "Iguana",
        "Impala",
        "Jaguar",
        "Jay",
        "Jellyfish",
        "Kangaroo",
        "Kingbird",
        "Kinkajou",
        "Kite",
        "Koala",
        "Komodo dragon",
        "Ladybug",
        "Lapwing",
        "Lark",
        "Lemur",
        "Leopard",
        "Lion",
        "Lizard",
        "Llama",
        "Lobster",
        "Locust",
        "Loris",
        "Louse",
        "Lyrebird",
        "Mallard",
        "Mammoth",
        "Manatee",
        "Mandrill",
        "Manta ray",
        "Mantis",
        "Meerkat",
        "Mink",
        "Mole",
        "Mongoose",
        "Monkey",
        "Moose",
        "Mosquito",
        "Mouse",
        "Narwhal",
        "Newt",
        "Nightingale",
        "Octopus",
        "Okapi",
        "Opossum",
        "Ostrich",
        "Otter",
        "OxSee Cattle",
        "Owl",
        "Oyster",
        "Panther",
        "Parrot",
        "Panda",
        "Partridge",
        "Peafowl",
        "Pelican",
        "Penguin",
        "Pheasant",
        "Pigeon",
        "Polar bear",
        "PonySee Horse",
        "Porcupine",
        "Porpoise",
        "Prairie dog",
        "Pug",
        "Quail",
        "Rabbit",
        "Raccoon",
        "Ram",
        "Rat",
        "Raven",
        "Red deer",
        "Red panda",
        "Rhinoceros",
        "Rook",
        "Salamander",
        "Salmon",
        "Sand dollar",
        "Sandpiper",
        "Sardine",
        "Sea lion",
        "Seahorse",
        "Seal",
        "Sea otter",
        "Sheep",
        "Shrew",
        "Skink",
        "Skipper",
        "Skunk",
        "Sloth",
        "Snail",
        "Snake",
        "Spider",
        "Spoonbill",
        "Squid",
        "Squirrel",
        "Starfish",
        "Starling",
        "Stilt",
        "Stingray",
        "Swan",
        "Tapir",
        "Tarsier",
        "Termite",
        "Thrush",
        "Tiger",
        "Toad",
        "Toucan",
        "Turkey",
        "Turtle",
        "Viper",
        "Wallaby",
        "Walrus",
        "Wasp",
        "Weasel",
        "Whale",
        "Wildebeest",
        "Wolf",
        "Wolverine",
        "Wombat",
        "Zebra"
    };

    private static readonly string[] Adjectives =
    {
        "Furious",
        "Glad",
        "Happy",
        "Perturbed",
        "Irritated",
        "Annoyed",
        "Frustrated",
        "Indignant",
        "Offended",
        "Angry",
        "Enraged",
        "Rampaging",
        "Upbeat",
        "Spirited",
        "Pleased",
        "Cheerful"
    };

    public static string GetName()
        => $"{GetAdjective()} {GetNoun()}";

    public static string GetNoun()
        => Nouns[Random.Shared.Next(0, Nouns.Length - 1)];

    public static string GetAdjective()
        => Adjectives[Random.Shared.Next(0, Adjectives.Length - 1)];
}
